# Generated by Django 4.2.7 on 2026-01-12 07:47

from django.db import migrations, models
import django.db.models.deletion
import hr_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('probation_letter', 'Probation Letter'), ('service_certificate', 'Service Certificate'), ('experience_certificate', 'Experience Certificate'), ('probation_note', 'Probation Note'), ('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('termination_letter', 'Termination Letter'), ('transfer_letter', 'Transfer Letter'), ('other', 'Other')], max_length=25)),
                ('template_file', models.FileField(upload_to=hr_portal.models.template_upload_path)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(choices=[('excel', 'Excel'), ('word', 'Word'), ('pdf', 'PDF'), ('other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to=hr_portal.models.employee_document_upload_path)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='hr_portal.employee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_portal.documenttemplate')),
            ],
        ),
    ]
