# Generated by Django 4.2.7 on 2026-01-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0003_probationnotification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('probation_letter', 'Probation Letter'), ('service_certificate', 'Service Certificate'), ('experience_certificate', 'Experience Certificate'), ('probation_note', 'Probation Note'), ('offer_letter', 'Offer Letter'), ('appointment_letter', 'Appointment Letter'), ('termination_letter', 'Termination Letter'), ('transfer_letter', 'Transfer Letter'), ('promotion_letter', 'Promotion Letter'), ('salary_increment_letter', 'Salary Increment Letter'), ('probation_extension_letter', 'Probation Extension Letter'), ('probation_draft', 'Probation Draft'), ('probation_evaluation_form', 'Probation Evaluation Form'), ('warning_letter', 'Warning Letter'), ('resignation_acceptance_letter', 'Resignation Acceptance Letter'), ('resignation_draft', 'Resignation Draft'), ('other', 'Other')], max_length=35),
        ),
    ]
