# Generated by Django 4.2.7 on 2026-01-15 11:02

from django.db import migrations, models
import django.db.models.deletion


def create_departments_from_existing_employees(apps, schema_editor):
    """
    Create Department objects for existing department names in employees.
    """
    Employee = apps.get_model('hr_portal', 'Employee')
    Department = apps.get_model('hr_portal', 'Department')

    # Get all unique department names from existing employees
    department_names = set()
    for emp in Employee.objects.all():
        if emp.department:  # Only consider non-empty department names
            department_names.add(emp.department)

    # Create Department objects for each unique department name
    for dept_name in department_names:
        Department.objects.get_or_create(
            name=dept_name,
            defaults={
                'email': 'muhammad.hamza@giki.edu.pk',  # Updated default email
                'description': f'Department for {dept_name}'
            }
        )


def update_employee_department_references(apps, schema_editor):
    """
    Update Employee records to use the new Department foreign key.
    """
    Employee = apps.get_model('hr_portal', 'Employee')
    Department = apps.get_model('hr_portal', 'Department')

    # For each employee, find the corresponding department and set the FK
    for employee in Employee.objects.all():
        # Get the old department name (still stored as a string in the old field)
        old_dept_name = employee.department  # This is the CharField value

        if old_dept_name:
            try:
                dept = Department.objects.get(name=old_dept_name)
                employee.department_new = dept  # This will be the new FK field
                employee.save()
            except Department.DoesNotExist:
                # If department doesn't exist, skip
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0004_alter_documenttemplate_template_type'),
    ]

    operations = [
        # First, create the Department model
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Email address for department head', max_length=254)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),

        # Add a temporary field to store the new department FK
        migrations.AddField(
            model_name='employee',
            name='department_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_portal.department'),
        ),

        # Run the data migration to create departments from existing employee data
        migrations.RunPython(create_departments_from_existing_employees),

        # Run the data migration to update employee department references
        migrations.RunPython(update_employee_department_references),

        # Remove the old department field (CharField)
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),

        # Rename the new department field to 'department'
        migrations.RenameField(
            model_name='employee',
            old_name='department_new',
            new_name='department',
        ),
    ]