# Generated by Django 4.2.7 on 2026-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0005_department_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extended_probation_end_date',
            field=models.DateField(blank=True, help_text='New end date if probation is extended', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_extended',
            field=models.BooleanField(default=False, help_text='Indicates if the probation period has been extended'),
        ),
        migrations.AddField(
            model_name='probationapproval',
            name='extended_end_date',
            field=models.DateField(blank=True, help_text='New end date after extension', null=True),
        ),
        migrations.AddField(
            model_name='probationapproval',
            name='extension_months',
            field=models.IntegerField(default=0, help_text='Number of months to extend probation'),
        ),
        migrations.AlterField(
            model_name='probationapproval',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('extended', 'Extended')], default='pending', max_length=20),
        ),
    ]
